(ns zapbot.golpes
  "Identidade dos golpes e nomes em português. Catálogo PokeAPI (2026-09-09).
  Traduções disponíveis em WatWowMap/pogo-data-api, complementadas por
  traduções locais do bot; não pressupõe nomes oficiais para todo o catálogo."
  (:require [clojure.string :as str]))

;; Fontes: https://github.com/PokeAPI/pokeapi/tree/master/data/v2/csv
;; https://github.com/WatWowMap/pogo-data-api/tree/master/data/v1/translations
(def nomes-pt
  {"10-000-000-volt-thunderbolt" "Raio de Dez Milhões de Volts"
   "absorb" "Absorção"
   "accelerock" "Rocha Veloz"
   "acid" "Ácido"
   "acid-armor" "Armadura Ácida"
   "acid-downpour--physical" "Dilúvio Ácido (Físico)"
   "acid-downpour--special" "Dilúvio Ácido (Especial)"
   "acid-spray" "Spray Ácido"
   "acrobatics" "Acrobático"
   "acupressure" "Acupressão"
   "aerial-ace" "Ás dos Ares"
   "aeroblast" "Explosão Aérea++"
   "after-you" "Depois de Você"
   "agility" "Agilidade"
   "air-cutter" "Cortador de Ar"
   "air-slash" "Golpe de Ar"
   "all-out-pummeling--physical" "Pancadaria Total (Físico)"
   "all-out-pummeling--special" "Pancadaria Total (Especial)"
   "alluring-voice" "Voz Sedutora"
   "ally-switch" "Troca Aliada"
   "amnesia" "Amnésia"
   "anchor-shot" "Disparo de Âncora"
   "ancient-power" "Poder Ancestral"
   "apple-acid" "Ácido de Maçã"
   "aqua-cutter" "Cortador Aquático"
   "aqua-jet" "Aqua Jato"
   "aqua-ring" "Anel de Água"
   "aqua-step" "Passo Aquático"
   "aqua-tail" "Aqua Cauda"
   "arm-thrust" "Golpes de Braço"
   "armor-cannon" "Canhão de Armadura"
   "aromatherapy" "Aromaterapia"
   "aromatic-mist" "Névoa Aromática"
   "assist" "Assistência"
   "assurance" "Garantia"
   "astonish" "Abismar"
   "astral-barrage" "Bombardeio Astral"
   "attack-order" "Ordem de Ataque"
   "attract" "Atração"
   "aura-sphere" "Aura Esférica"
   "aura-wheel" "Roda de Aura"
   "aurora-beam" "Raio Aurora"
   "aurora-veil" "Véu Aurora"
   "autotomize" "Autotomia"
   "avalanche" "Avalanche"
   "axe-kick" "Chute Machado"
   "baby-doll-eyes" "Olhar Meigo"
   "baddy-bad" "Maldade Sombria"
   "baneful-bunker" "Bunker Venenoso"
   "barb-barrage" "Bombardeio de Farpas"
   "barrage" "Bombardeio"
   "barrier" "Barreira"
   "baton-pass" "Passar o Bastão"
   "beak-blast" "Bico Explosivo"
   "beat-up" "Espancamento"
   "behemoth-bash" "Pancada Colossal"
   "behemoth-blade" "Espada Colossal"
   "belch" "Arrotar"
   "belly-drum" "Tambor de Barriga"
   "bestow" "Presentear"
   "bide" "Paciência"
   "bind" "Amarrar"
   "bite" "Mordida"
   "bitter-blade" "Lâmina Amarga"
   "bitter-malice" "Malícia Amarga"
   "black-hole-eclipse--physical" "Eclipse do Buraco Negro (Físico)"
   "black-hole-eclipse--special" "Eclipse do Buraco Negro (Especial)"
   "blast-burn" "Queimadura Explosiva"
   "blaze-kick" "Chute Labareda"
   "blazing-torque" "Torque Flamejante"
   "bleakwind-storm" "Tempestade Álgida"
   "blizzard" "Nevasca"
   "block" "Bloqueio"
   "blood-moon" "Lua de Sangue"
   "bloom-doom--physical" "Florescimento Fatal (Físico)"
   "bloom-doom--special" "Florescimento Fatal (Especial)"
   "blue-flare" "Chama Azul"
   "body-press" "Prensa Corporal"
   "body-slam" "Pancada Corporal"
   "bolt-beak" "Bico Elétrico"
   "bolt-strike" "Ataque Relâmpago"
   "bone-club" "Bastão de Osso"
   "bone-rush" "Ataque de Ossos"
   "bonemerang" "Osso Bumerangue"
   "boomburst" "Rajada Explosiva"
   "bounce" "Salto"
   "bouncy-bubble" "Bolha Saltitante"
   "branch-poke" "Cutucada de Galho"
   "brave-bird" "Pássaro Bravo"
   "breaking-swipe" "Golpe Deslizante"
   "breakneck-blitz--physical" "Investida Fulminante (Físico)"
   "breakneck-blitz--special" "Investida Fulminante (Especial)"
   "brick-break" "Quebra-telha"
   "brine" "Salmoura"
   "brutal-swing" "Balanço Violento"
   "bubble" "Bolha"
   "bubble-beam" "Jato de Bolhas"
   "bug-bite" "Picada"
   "bug-buzz" "Zumbido de Inseto"
   "bulk-up" "Fortalecer"
   "bulldoze" "Tremor"
   "bullet-punch" "Soco Projétil"
   "bullet-seed" "Projétil de Semente"
   "burn-up" "Combustão Total"
   "burning-bulwark" "Baluarte Ardente"
   "burning-jealousy" "Ciúme Ardente"
   "buzzy-buzz" "Zumbido Elétrico"
   "calm-mind" "Mente Calma"
   "camouflage" "Camuflagem"
   "captivate" "Cativar"
   "catastropika" "Catastropika"
   "ceaseless-edge" "Lâmina Incessante"
   "celebrate" "Comemorar"
   "charge" "Carregar"
   "charge-beam" "Carga de Raio"
   "charm" "Encantar"
   "chatter" "Tagarelar"
   "chilling-water" "Água Fria"
   "chilly-reception" "Recepção Gelada"
   "chip-away" "Desbastar"
   "chloroblast" "Explosão de Clorofila"
   "circle-throw" "Arremesso Circular"
   "clamp" "Prender"
   "clanging-scales" "Batida de Escamas"
   "clangorous-soul" "Alma Clamorosa"
   "clangorous-soulblaze" "Chama da Alma Clamorosa"
   "clear-smog" "Fumaça Purificadora"
   "close-combat" "Corpo-a-corpo"
   "coaching" "Treinamento"
   "coil" "Enrolar"
   "collision-course" "Rota de Colisão"
   "combat-torque" "Torque de Combate"
   "comet-punch" "Soco Cometa"
   "comeuppance" "Acerto de Contas"
   "confide" "Confidência"
   "confuse-ray" "Raio Confuso"
   "confusion" "Confusão"
   "constrict" "Constrição"
   "continental-crush--physical" "Esmagamento Continental (Físico)"
   "continental-crush--special" "Esmagamento Continental (Especial)"
   "conversion" "Conversão"
   "conversion-2" "Conversão 2"
   "copycat" "Copiar"
   "core-enforcer" "Imposição do Núcleo"
   "corkscrew-crash--physical" "Impacto Espiral (Físico)"
   "corkscrew-crash--special" "Impacto Espiral (Especial)"
   "corrosive-gas" "Gás Corrosivo"
   "cosmic-power" "Poder Cósmico"
   "cotton-guard" "Proteção de Algodão"
   "cotton-spore" "Esporos de Algodão"
   "counter" "Contra-atacar"
   "court-change" "Troca de Campo"
   "covet" "Cobiçar"
   "crabhammer" "Martelo Caranguejo"
   "crafty-shield" "Escudo Astuto"
   "cross-chop" "Golpe Cruzado"
   "cross-poison" "Corte-veneno"
   "crunch" "Mastigada"
   "crush-claw" "Garra Esmagadora"
   "crush-grip" "Aperto Esmagador"
   "curse" "Maldição"
   "cut" "Cortar"
   "dark-pulse" "Pulso Sombrio"
   "dark-void" "Dark Void"
   "darkest-lariat" "Lariat Escuro"
   "dazzling-gleam" "Clarão Deslumbrante"
   "decorate" "Decorar"
   "defend-order" "Ordem de Defesa"
   "defense-curl" "Enrolar Defensivo"
   "defog" "Desembaçar"
   "destiny-bond" "Laço do Destino"
   "detect" "Detectar"
   "devastating-drake--physical" "Dragão Devastador (Físico)"
   "devastating-drake--special" "Dragão Devastador (Especial)"
   "diamond-storm" "Tempestade de Diamantes"
   "dig" "Cavar"
   "dire-claw" "Garra Funesta"
   "disable" "Desabilitar"
   "disarming-voice" "Voz Desarmante"
   "discharge" "Descarga"
   "dive" "Mergulho"
   "dizzy-punch" "Soco Atordoante"
   "doodle" "Rabisco"
   "doom-desire" "Desejo Cruel"
   "double-edge" "Faca de Dois Gumes"
   "double-hit" "Golpe Duplo"
   "double-iron-bash" "Pancada de Ferro Dupla"
   "double-kick" "Chute Duplo"
   "double-shock" "Choque Duplo"
   "double-slap" "Tapa Duplo"
   "double-team" "Multiplicar"
   "draco-meteor" "Meteoro do Dragão"
   "dragon-ascent" "Ascenção do Dragão"
   "dragon-breath" "Sopro do Dragão"
   "dragon-cheer" "Incentivo do Dragão"
   "dragon-claw" "Garra de Dragão"
   "dragon-dance" "Dança do Dragão"
   "dragon-darts" "Dardos do Dragão"
   "dragon-energy" "Energia Dracônica"
   "dragon-hammer" "Martelo do Dragão"
   "dragon-pulse" "Pulso do Dragão"
   "dragon-rage" "Fúria do Dragão"
   "dragon-rush" "Investida do Dragão"
   "dragon-tail" "Cauda do Dragão"
   "drain-punch" "Soco Dreno"
   "draining-kiss" "Beijo Drenante"
   "dream-eater" "Devorador de Sonhos"
   "drill-peck" "Bico Broca"
   "drill-run" "Furação"
   "drum-beating" "Toque do Tambor"
   "dual-chop" "Corte Duplo"
   "dual-wingbeat" "Batida Dupla de Asas"
   "dynamax-cannon" "Canhão Dinamax"
   "dynamic-punch" "Soco Dinâmico"
   "earth-power" "Poder da Terra"
   "earthquake" "Terremoto"
   "echoed-voice" "Voz Ecoante"
   "eerie-impulse" "Impulso Sinistro"
   "eerie-spell" "Feitiço Sinistro"
   "egg-bomb" "Bomba de Ovo"
   "electric-terrain" "Campo Elétrico"
   "electrify" "Eletrificar"
   "electro-ball" "Bola Elétrica"
   "electro-drift" "Derrapagem Elétrica"
   "electro-shot" "Disparo Elétrico"
   "electroweb" "Teia Elétrica"
   "embargo" "Embargo"
   "ember" "Brasa"
   "encore" "Bis"
   "endeavor" "Esforço"
   "endure" "Resistir"
   "energy-ball" "Bola de Energia"
   "entrainment" "Sincronizar"
   "eruption" "Erupção"
   "esper-wing" "Asa Psíquica"
   "eternabeam" "Raio Eterno"
   "expanding-force" "Força Expansiva"
   "explosion" "Explosão"
   "extrasensory" "Extrassensorial"
   "extreme-evoboost" "Impulso Evolutivo Extremo"
   "extreme-speed" "Velocidade Extrema"
   "facade" "Fachada"
   "fairy-lock" "Trava de Fada"
   "fairy-wind" "Vento de Fada"
   "fake-out" "Surpresa"
   "fake-tears" "Lágrimas Falsas"
   "false-surrender" "Falsa Rendição"
   "false-swipe" "Golpe Falso"
   "feather-dance" "Dança das Penas"
   "feint" "Finta"
   "feint-attack" "Ataque Dissimulado"
   "fell-stinger" "Ferrão Letal"
   "fickle-beam" "Raio Inconstante"
   "fiery-dance" "Fiery Dance"
   "fiery-wrath" "Fúria Ardente"
   "fillet-away" "Filetar"
   "final-gambit" "Aposta Final"
   "fire-blast" "Rajada de Fogo"
   "fire-fang" "Presas de Fogo"
   "fire-lash" "Chicote de Fogo"
   "fire-pledge" "Pacto de Fogo"
   "fire-punch" "Soco de Fogo"
   "fire-spin" "Chama Furacão"
   "first-impression" "Primeira Impressão"
   "fishious-rend" "Rasgo de Peixe"
   "fissure" "Fissura"
   "flail" "Debater-se"
   "flame-burst" "Rajada de Chamas"
   "flame-charge" "Ataque de Chamas"
   "flame-wheel" "Roda de Fogo"
   "flamethrower" "Lança-chamas"
   "flare-blitz" "Investida Flamejante"
   "flash" "Clarão"
   "flash-cannon" "Canhão de Flash"
   "flatter" "Bajular"
   "fleur-cannon" "Canhão Floral"
   "fling" "Lançamento"
   "flip-turn" "Virada Aquática"
   "floaty-fall" "Queda Flutuante"
   "floral-healing" "Cura Floral"
   "flower-shield" "Escudo de Flores"
   "flower-trick" "Truque Floral"
   "fly" "Voar"
   "flying-press" "Aperto Voador"
   "focus-blast" "Explosão Focalizada"
   "focus-energy" "Concentrar Energia"
   "focus-punch" "Soco Focalizado"
   "follow-me" "Siga-me"
   "force-palm" "Palma da Força"
   "foresight" "Previsão"
   "forests-curse" "Maldição da Floresta"
   "foul-play" "Jogo Sujo"
   "freeze-dry" "Liofilização"
   "freeze-shock" "Choque Congelante"
   "freezing-glare" "Olhar Congelante"
   "freezy-frost" "Geada Congelante"
   "frenzy-plant" "Planta Mortal"
   "frost-breath" "Respiração de Gelo"
   "frustration" "Frustração"
   "fury-attack" "Ataque de Fúria"
   "fury-cutter" "Cortador de Fúria"
   "fury-swipes" "Arranhões Furiosos"
   "fusion-bolt" "Raio de Fusão"
   "fusion-flare" "Chama da Fusão"
   "future-sight" "Visão do Futuro"
   "gastro-acid" "Ácido Gástrico"
   "gear-grind" "Moagem de Engrenagens"
   "gear-up" "Preparar Engrenagens"
   "genesis-supernova" "Supernova da Gênese"
   "geomancy" "Geomancia"
   "giga-drain" "Gigadreno"
   "giga-impact" "Gigaimpacto"
   "gigaton-hammer" "Martelo Gigatônico"
   "gigavolt-havoc--physical" "Devastação Gigavolt (Físico)"
   "gigavolt-havoc--special" "Devastação Gigavolt (Especial)"
   "glacial-lance" "Lança Glacial"
   "glaciate" "Glaciar"
   "glaive-rush" "Fúria de Glaive"
   "glare" "Olhar Paralisante"
   "glitzy-glow" "Brilho Reluzente"
   "grass-knot" "Nó de Grama"
   "grass-pledge" "Pacto de Grama"
   "grass-whistle" "Assobio de Grama"
   "grassy-glide" "Deslize de Grama"
   "grassy-terrain" "Campo de Grama"
   "grav-apple" "Maçã Gravitacional"
   "gravity" "Gravidade"
   "growl" "Rosnar"
   "growth" "Crescimento"
   "grudge" "Ressentimento"
   "guard-split" "Dividir Defesa"
   "guard-swap" "Troca de Defesa"
   "guardian-of-alola" "Guardião de Alola"
   "guillotine" "Guilhotina"
   "gunk-shot" "Tiro de Sujeira"
   "gust" "Lufada de Vento"
   "gyro-ball" "Girobola"
   "hail" "Granizo"
   "hammer-arm" "Braço Martelo"
   "happy-hour" "Hora Feliz"
   "hard-press" "Prensa Pesada"
   "harden" "Endurecer"
   "haze" "Neblina"
   "head-charge" "Investida de Cabeça"
   "head-smash" "Esmagamento de Cabeça"
   "headbutt" "Cabeçada"
   "headlong-rush" "Investida Imprudente"
   "heal-bell" "Sino Curativo"
   "heal-block" "Bloqueio de Cura"
   "heal-order" "Ordem de Cura"
   "heal-pulse" "Pulso Curativo"
   "healing-wish" "Desejo de Cura"
   "heart-stamp" "Estampa de Coração"
   "heart-swap" "Troca de Corações"
   "heat-crash" "Choque de Calor"
   "heat-wave" "Onda de Calor"
   "heavy-slam" "Golpe Pesado"
   "helping-hand" "Mão Amiga"
   "hex" "Feitiço"
   "hidden-power" "Poder Oculto"
   "high-horsepower" "Potência Equina"
   "high-jump-kick" "Chute de Pulo Alto"
   "hold-back" "Conter-se"
   "hold-hands" "Dar as Mãos"
   "hone-claws" "Afiar Garras"
   "horn-attack" "Ataque de Chifre"
   "horn-drill" "Chifre Broca"
   "horn-leech" "Chifre Sanguessuga"
   "howl" "Uivo"
   "hurricane" "Furacão"
   "hydro-cannon" "Hidro Canhão"
   "hydro-pump" "Jato d'Água"
   "hydro-steam" "Vapor Aquático"
   "hydro-vortex--physical" "Vórtice Aquático (Físico)"
   "hydro-vortex--special" "Vórtice Aquático (Especial)"
   "hyper-beam" "Hiper-raio"
   "hyper-drill" "Hiperbroca"
   "hyper-fang" "Hiperpresa"
   "hyper-voice" "Hipervoz"
   "hyperspace-fury" "Fúria de Hiperespaço"
   "hyperspace-hole" "Fenda de Hiperespaço"
   "hypnosis" "Hipnose"
   "ice-ball" "Bola de Gelo"
   "ice-beam" "Raio Congelante"
   "ice-burn" "Queimadura de Gelo"
   "ice-fang" "Presa de Gelo"
   "ice-hammer" "Martelo de Gelo"
   "ice-punch" "Soco de Gelo"
   "ice-shard" "Caco de Gelo"
   "ice-spinner" "Giro de Gelo"
   "icicle-crash" "Queda de Estalactites"
   "icicle-spear" "Lança Congelada"
   "icy-wind" "Vento Congelante"
   "imprison" "Aprisionar"
   "incinerate" "Incinerar"
   "infernal-parade" "Desfile Infernal"
   "inferno" "Inferno"
   "inferno-overdrive--physical" "Inferno Supremo (Físico)"
   "inferno-overdrive--special" "Inferno Supremo (Especial)"
   "infestation" "Infestação"
   "ingrain" "Enraizar"
   "instruct" "Instruir"
   "ion-deluge" "Dilúvio de Íons"
   "iron-defense" "Defesa de Ferro"
   "iron-head" "Cabeça de Ferro"
   "iron-tail" "Cauda de Ferro"
   "ivy-cudgel" "Clava de Hera"
   "jaw-lock" "Trava de Mandíbula"
   "jet-punch" "Soco a Jato"
   "judgment" "Julgamento"
   "jump-kick" "Chute Saltador"
   "jungle-healing" "Cura da Selva"
   "karate-chop" "Golpe de Caratê"
   "kinesis" "Cinese"
   "kings-shield" "Escudo do Rei"
   "knock-off" "Desarmar"
   "kowtow-cleave" "Corte Reverente"
   "lands-wrath" "Ira da Terra"
   "laser-focus" "Foco Laser"
   "lash-out" "Revide Furioso"
   "last-resort" "Último Recurso"
   "last-respects" "Últimas Homenagens"
   "lava-plume" "Pluma de Lava"
   "leaf-blade" "Lâmina de Folha"
   "leaf-storm" "Tempestade de Folhas"
   "leaf-tornado" "Tornado de Folhas"
   "leafage" "Folhagem"
   "leech-life" "Suga-vidas"
   "leech-seed" "Semente Sanguessuga"
   "leer" "Encarar"
   "lets-snuggle-forever" "Abraço Eterno"
   "lick" "Lambida"
   "life-dew" "Orvalho Vital"
   "light-of-ruin" "Luz da Ruína"
   "light-screen" "Tela de Luz"
   "light-that-burns-the-sky" "Luz que Incinera o Céu"
   "liquidation" "Aquaríete"
   "lock-on" "Mirar"
   "lovely-kiss" "Beijo Amoroso"
   "low-kick" "Rasteira"
   "low-sweep" "Movimento Baixo"
   "lucky-chant" "Canto da Sorte"
   "lumina-crash" "Choque Luminoso"
   "lunar-blessing" "Bênção Lunar"
   "lunar-dance" "Dança Lunar"
   "lunge" "Estocada"
   "luster-purge" "Purga de Esplendor"
   "mach-punch" "Soco Rápido"
   "magic-coat" "Manto Mágico"
   "magic-powder" "Pó Mágico"
   "magic-room" "Espaço Mágico"
   "magical-leaf" "Folha Mágica"
   "magical-torque" "Torque Mágico"
   "magma-storm" "Tempestade de Magma"
   "magnet-bomb" "Bomba Ímã"
   "magnet-rise" "Levitação Magnética"
   "magnetic-flux" "Fluxo Magnético"
   "magnitude" "Magnitude"
   "make-it-rain" "Chuva de Ouro"
   "malicious-moonsault" "Salto Lunar Malicioso"
   "malignant-chain" "Corrente Maligna"
   "mat-block" "Bloqueio de Tatame"
   "matcha-gotcha" "Surpresa de Matchá"
   "max-airstream" "Corrente de Ar Max"
   "max-darkness" "Escuridão Max"
   "max-flare" "Chama Max"
   "max-flutterby" "Nuvem de Inseto Max"
   "max-geyser" "Gêiser Max"
   "max-guard" "Defesa Max"
   "max-hailstorm" "Temporal de Granizo Max"
   "max-knuckle" "Punho Max"
   "max-lightning" "Raio Max"
   "max-mindstorm" "Tempestade Mental Max"
   "max-ooze" "Corrosão Max"
   "max-overgrowth" "Flora Max"
   "max-phantasm" "Espectro Max"
   "max-quake" "Oscilação Max"
   "max-rockfall" "Desabamento Max"
   "max-starfall" "Queda Estelar Max"
   "max-steelspike" "Espinho de Aço Max"
   "max-strike" "Golpe Max"
   "max-wyrmwind" "Bafo Dracônico Max"
   "me-first" "Eu Primeiro"
   "mean-look" "Olhar Malvado"
   "meditate" "Meditar"
   "mega-drain" "Megadreno"
   "mega-kick" "Mega Chute"
   "mega-punch" "Mega Soco"
   "megahorn" "Megachifre"
   "memento" "Lembrança"
   "menacing-moonraze-maelstrom" "Turbilhão Lunar Ameaçador"
   "metal-burst" "Explosão Metálica"
   "metal-claw" "Garra de Metal"
   "metal-sound" "Som de Metal"
   "meteor-assault" "Assalto Meteórico"
   "meteor-beam" "Raio Meteórico"
   "meteor-mash" "Meteoro Esmagador"
   "metronome" "Metrônomo"
   "mighty-cleave" "Corte Poderoso"
   "milk-drink" "Beber Leite"
   "mimic" "Imitação"
   "mind-blown" "Explosão Mental"
   "mind-reader" "Leitor de Mentes"
   "minimize" "Minimizar"
   "miracle-eye" "Olho Milagroso"
   "mirror-coat" "Casaco Espelhado"
   "mirror-move" "Movimento Espelho"
   "mirror-shot" "Tiro no Espelho"
   "mist" "Névoa"
   "mist-ball" "Bola de Névoa"
   "misty-explosion" "Explosão Nebulosa"
   "misty-terrain" "Campo de Névoa"
   "moonblast" "Explosão Lunar"
   "moongeist-beam" "Feixe Espectral"
   "moonlight" "Luz do Luar"
   "morning-sun" "Sol da Manhã"
   "mortal-spin" "Giro Mortal"
   "mountain-gale" "Vendaval da Montanha"
   "mud-bomb" "Bomba de Lama"
   "mud-shot" "Tiro de Lama"
   "mud-slap" "Tapa de Lama"
   "mud-sport" "Banho de Lama"
   "muddy-water" "Água Barrenta"
   "multi-attack" "Ataque Múltiplo"
   "mystical-fire" "Fogo Místico"
   "mystical-power" "Poder Místico"
   "nasty-plot" "Plano Maligno"
   "natural-gift" "Dom Natural"
   "nature-power" "Poder da Natureza"
   "natures-madness" "Ira da Natureza"
   "needle-arm" "Braço de Agulhas"
   "never-ending-nightmare--physical" "Pesadelo Sem Fim (Físico)"
   "never-ending-nightmare--special" "Pesadelo Sem Fim (Especial)"
   "night-daze" "Ofuscamento Noturno"
   "night-shade" "Sombra Noturna"
   "night-slash" "Talho Noturno"
   "nightmare" "Pesadelo"
   "no-retreat" "Sem Recuar"
   "noble-roar" "Rugido Nobre"
   "noxious-torque" "Torque Nocivo"
   "nuzzle" "Aconchego"
   "oblivion-wing" "Asa do Esquecimento"
   "obstruct" "Obstruir"
   "oceanic-operetta" "Opereta Oceânica"
   "octazooka" "Polvo-canhão"
   "octolock" "Trava de Tentáculos"
   "odor-sleuth" "Farejar"
   "ominous-wind" "Vento Ominoso"
   "order-up" "Pedido Pronto"
   "origin-pulse" "Pulso Original"
   "outrage" "Ultraje"
   "overdrive" "Sobrecarga"
   "overheat" "Superaquecimento"
   "pain-split" "Dividir Dor"
   "parabolic-charge" "Ataque Parabólico"
   "parting-shot" "Golpe de Despedida"
   "pay-day" "Dia de Pagamento"
   "payback" "Revide"
   "peck" "Bicada"
   "perish-song" "Canção da Perdição"
   "petal-blizzard" "Nevasca de Pétalas"
   "petal-dance" "Dança das Pétalas"
   "phantom-force" "Força Fantasma"
   "photon-geyser" "Gêiser de Fótons"
   "pika-papow" "Pikapancada"
   "pin-missile" "Míssil de Espinhos"
   "plasma-fists" "Punhos de Plasma"
   "play-nice" "Brincar Amigavelmente"
   "play-rough" "Jogo Duro"
   "pluck" "Bicar"
   "poison-fang" "Presa Venenosa"
   "poison-gas" "Gás Venenoso"
   "poison-jab" "Golpe Envenenado"
   "poison-powder" "Pó Venenoso"
   "poison-sting" "Ferrão Venenoso"
   "poison-tail" "Cauda Venenosa"
   "pollen-puff" "Bola de Pólen"
   "poltergeist" "Poltergeist"
   "population-bomb" "Bomba Populacional"
   "pounce" "Bote"
   "pound" "Pancada"
   "powder" "Pólvora"
   "powder-snow" "Neve em Pó"
   "power-gem" "Gema Poderosa"
   "power-shift" "Mudança de Poder"
   "power-split" "Dividir Poder"
   "power-swap" "Troca de Poder"
   "power-trick" "Truque de Poder"
   "power-trip" "Excesso de Poder"
   "power-up-punch" "Soco Empoderador"
   "power-whip" "Chicote Poderoso"
   "precipice-blades" "Lâmina Abissal"
   "present" "Presente"
   "prismatic-laser" "Laser Prismático"
   "protect" "Proteção"
   "psybeam" "Feixe Psíquico"
   "psyblade" "Lâmina Psíquica"
   "psych-up" "Autoestímulo"
   "psychic" "Psíquico"
   "psychic-fangs" "Caninos Psíquicos"
   "psychic-noise" "Ruído Psíquico"
   "psychic-terrain" "Campo Psíquico"
   "psycho-boost" "Impulso Psíquico"
   "psycho-cut" "Corte Psíquico"
   "psycho-shift" "Transferência Psíquica"
   "psyshield-bash" "Investida de Escudo Psíquico"
   "psyshock" "Choque Psíquico"
   "psystrike" "Golpe Psíquico"
   "psywave" "Onda Psíquica"
   "pulverizing-pancake" "Panqueca Pulverizadora"
   "punishment" "Punição"
   "purify" "Purificar"
   "pursuit" "Perseguição"
   "pyro-ball" "Bola Incendiária"
   "quash" "Suprimir"
   "quick-attack" "Ataque Rápido"
   "quick-guard" "Proteção Rápida"
   "quiver-dance" "Dança das Asas"
   "rage" "Raiva"
   "rage-fist" "Punho Feroz"
   "rage-powder" "Pó de Raiva"
   "raging-bull" "Touro Furioso"
   "raging-fury" "Fúria Desenfreada"
   "rain-dance" "Dança da Chuva"
   "rapid-spin" "Giro Rápido"
   "razor-leaf" "Folha Navalha"
   "razor-shell" "Concha Navalha"
   "razor-wind" "Vento Cortante"
   "recover" "Recuperação"
   "recycle" "Reciclar"
   "reflect" "Refletir"
   "reflect-type" "Refletir Tipo"
   "refresh" "Renovar"
   "relic-song" "Relic Song"
   "rest" "Descansar"
   "retaliate" "Retaliação"
   "return" "Retorno"
   "revelation-dance" "Dança da Revelação"
   "revenge" "Revanche"
   "reversal" "Reversão"
   "revival-blessing" "Bênção de Ressurreição"
   "rising-voltage" "Voltagem Crescente"
   "roar" "Rugido"
   "roar-of-time" "Rugido do Tempo"
   "rock-blast" "Explosão de Rocha"
   "rock-climb" "Escalada"
   "rock-polish" "Polimento de Rocha"
   "rock-slide" "Deslize de Pedras"
   "rock-smash" "Esmagamento de Pedras"
   "rock-throw" "Arremesso de Pedra"
   "rock-tomb" "Tumba de Rochas"
   "rock-wrecker" "Demolidor de Pedras"
   "role-play" "Interpretação"
   "rolling-kick" "Chute Giratório"
   "rollout" "Rolagem"
   "roost" "Pousar"
   "rototiller" "Arar"
   "round" "Cânone"
   "ruination" "Ruína"
   "sacred-fire" "Fogo Sagrado++"
   "sacred-sword" "Espada Sagrada"
   "safeguard" "Salvaguarda"
   "salt-cure" "Cura de Sal"
   "sand-attack" "Ataque de Areia"
   "sand-tomb" "Fosso de Areia"
   "sandsear-storm" "Tempestade Saibrosa"
   "sandstorm" "Tempestade de Areia"
   "sappy-seed" "Semente Seivosa"
   "savage-spin-out--physical" "Espiral Selvagem (Físico)"
   "savage-spin-out--special" "Espiral Selvagem (Especial)"
   "scald" "Escaldada"
   "scale-shot" "Disparo de Escamas"
   "scary-face" "Cara Assustadora"
   "scorching-sands" "Areias Ardentes"
   "scratch" "Arranhão"
   "screech" "Guincho"
   "searing-shot" "Disparo Escaldante"
   "searing-sunraze-smash" "Impacto Solar Escaldante"
   "secret-power" "Poder Secreto"
   "secret-sword" "Espada Secreta"
   "seed-bomb" "Bomba de Sementes"
   "seed-flare" "Semente Ofuscante"
   "seismic-toss" "Arremesso Sísmico"
   "self-destruct" "Autodestruição"
   "shadow-ball" "Bola Sombria"
   "shadow-blast" "Explosão Sombria"
   "shadow-blitz" "Assalto Sombrio"
   "shadow-bolt" "Raio Sombrio"
   "shadow-bone" "Osso Sombrio"
   "shadow-break" "Quebra Sombria"
   "shadow-chill" "Frio Sombrio"
   "shadow-claw" "Garra Sombria"
   "shadow-down" "Queda Sombria"
   "shadow-end" "Fim Sombrio"
   "shadow-fire" "Fogo Sombrio"
   "shadow-force" "Força das Sombras"
   "shadow-half" "Metade Sombria"
   "shadow-hold" "Prisão Sombria"
   "shadow-mist" "Névoa Sombria"
   "shadow-panic" "Pânico Sombrio"
   "shadow-punch" "Soco Sombrio"
   "shadow-rave" "Delírio Sombrio"
   "shadow-rush" "Investida Sombria"
   "shadow-shed" "Desprendimento Sombrio"
   "shadow-sky" "Céu Sombrio"
   "shadow-sneak" "Furtividade nas Sombras"
   "shadow-storm" "Tempestade Sombria"
   "shadow-wave" "Onda Sombria"
   "sharpen" "Afiar"
   "shattered-psyche--physical" "Ruptura Psíquica (Físico)"
   "shattered-psyche--special" "Ruptura Psíquica (Especial)"
   "shed-tail" "Soltar a Cauda"
   "sheer-cold" "Frio Absoluto"
   "shell-side-arm" "Arma de Concha"
   "shell-smash" "Quebra-casco"
   "shell-trap" "Armadilha de Casco"
   "shelter" "Abrigo"
   "shift-gear" "Troca de Marcha"
   "shock-wave" "Onda Elétrica"
   "shore-up" "Reforço de Areia"
   "signal-beam" "Feixe Sinalizador"
   "silk-trap" "Armadilha de Seda"
   "silver-wind" "Vento Prateado"
   "simple-beam" "Raio Simples"
   "sing" "Cantar"
   "sinister-arrow-raid" "Chuva de Flechas Sinistras"
   "sizzly-slide" "Deslize Flamejante"
   "sketch" "Esboço"
   "skill-swap" "Troca de Habilidades"
   "skitter-smack" "Golpe Rastejante"
   "skull-bash" "Quebra-crânio"
   "sky-attack" "Ataque do Céu"
   "sky-drop" "Queda Livre"
   "sky-uppercut" "Gancho Celeste"
   "slack-off" "Relaxar"
   "slam" "Pancada Brusca"
   "slash" "Talho"
   "sleep-powder" "Pó do Sono"
   "sleep-talk" "Falar Dormindo"
   "sludge" "Ataque de Lama"
   "sludge-bomb" "Bomba de Lodo"
   "sludge-wave" "Onda de Lama"
   "smack-down" "Derrubada"
   "smart-strike" "Golpe Certeiro"
   "smelling-salts" "Sais Aromáticos"
   "smog" "Nevoeiro de Fumaça"
   "smokescreen" "Cortina de Fumaça"
   "snap-trap" "Armadilha de Mandíbula"
   "snarl" "Rosnado"
   "snatch" "Arrebatar"
   "snipe-shot" "Tiro Certeiro"
   "snore" "Ronco"
   "snowscape" "Paisagem Nevada"
   "soak" "Encharcar"
   "soft-boiled" "Ovo Cozido"
   "solar-beam" "Raio Solar"
   "solar-blade" "Lâmina Solar"
   "sonic-boom" "Estrondo Sônico"
   "soul-stealing-7-star-strike" "Golpe das Sete Estrelas Rouba-almas"
   "spacial-rend" "Laceração Espacial"
   "spark" "Faísca"
   "sparkling-aria" "Aria Cintilante"
   "sparkly-swirl" "Espiral Cintilante"
   "spectral-thief" "Ladrão Espectral"
   "speed-swap" "Troca de Velocidade"
   "spicy-extract" "Extrato Picante"
   "spider-web" "Teia de Aranha"
   "spike-cannon" "Canhão de Espinhos"
   "spikes" "Espinhos"
   "spiky-shield" "Escudo Espinhoso"
   "spin-out" "Derrapagem"
   "spirit-break" "Quebra de Espírito"
   "spirit-shackle" "Manilha Sombria"
   "spit-up" "Cuspir"
   "spite" "Rancor"
   "splash" "Borrifada"
   "splintered-stormshards" "Tempestade de Fragmentos"
   "splishy-splash" "Onda Brincalhona"
   "spore" "Esporos"
   "spotlight" "Holofote"
   "springtide-storm" "Tempestade Primaveril"
   "stealth-rock" "Pedras Ocultas"
   "steam-eruption" "Erupção de Vapor"
   "steamroller" "Rolo Compressor"
   "steel-beam" "Raio de Aço"
   "steel-roller" "Rolo de Aço"
   "steel-wing" "Asa de Aço"
   "sticky-web" "Teia Pegajosa"
   "stockpile" "Estocar"
   "stoked-sparksurfer" "Surfista de Faíscas"
   "stomp" "Pisotear"
   "stomping-tantrum" "Pisoteio Furioso"
   "stone-axe" "Machado de Pedra"
   "stone-edge" "Gume de Pedra"
   "stored-power" "Poder Armazenado"
   "storm-throw" "Arremesso Tempestuoso"
   "strange-steam" "Vapor Estranho"
   "strength" "Força"
   "strength-sap" "Drenar Força"
   "string-shot" "Disparo de Fio"
   "struggle" "Insistência"
   "struggle-bug" "Ira de Inseto"
   "stuff-cheeks" "Encher as Bochechas"
   "stun-spore" "Esporos Paralisantes"
   "submission" "Submissão"
   "substitute" "Substituto"
   "subzero-slammer--physical" "Impacto Subzero (Físico)"
   "subzero-slammer--special" "Impacto Subzero (Especial)"
   "sucker-punch" "Soco Enganador"
   "sunny-day" "Dia Ensolarado"
   "sunsteel-strike" "Ataque Solaraço"
   "super-fang" "Super Presa"
   "supercell-slam" "Impacto de Supercélula"
   "superpower" "Superpoder"
   "supersonic" "Supersônico"
   "supersonic-skystrike--physical" "Ataque Aéreo Supersônico (Físico)"
   "supersonic-skystrike--special" "Ataque Aéreo Supersônico (Especial)"
   "surf" "Surfar"
   "surging-strikes" "Golpes Torrenciais"
   "swagger" "Arrogância"
   "swallow" "Engolir"
   "sweet-kiss" "Beijo Doce"
   "sweet-scent" "Aroma Doce"
   "swift" "Ataque Veloz"
   "switcheroo" "Troca Ardilosa"
   "swords-dance" "Dança das Espadas"
   "synchronoise" "Barulho Sincronizado"
   "synthesis" "Síntese"
   "syrup-bomb" "Bomba de Xarope"
   "tachyon-cutter" "Cortador de Táquions"
   "tackle" "Investida"
   "tail-glow" "Cauda Brilhante"
   "tail-slap" "Tapa de Cauda"
   "tail-whip" "Chicote de Cauda"
   "tailwind" "Vento de Cauda"
   "take-down" "Desmantelar"
   "take-heart" "Encorajar-se"
   "tar-shot" "Disparo de Piche"
   "taunt" "Provocação"
   "tearful-look" "Olhar Lacrimoso"
   "teatime" "Hora do Chá"
   "techno-blast" "Rajada Tecnológica"
   "tectonic-rage--physical" "Fúria Tectônica (Físico)"
   "tectonic-rage--special" "Fúria Tectônica (Especial)"
   "teeter-dance" "Dança Cambaleante"
   "telekinesis" "Telecinese"
   "teleport" "Teletransporte"
   "temper-flare" "Chama Temperamental"
   "tera-blast" "Rajada Tera"
   "tera-starstorm" "Tempestade Estelar Tera"
   "terrain-pulse" "Pulso do Campo"
   "thief" "Ladrão"
   "thousand-arrows" "Mil Flechas"
   "thousand-waves" "Mil Ondas"
   "thrash" "Surra"
   "throat-chop" "Golpe na Garganta"
   "thunder" "Trovão"
   "thunder-cage" "Prisão Elétrica"
   "thunder-fang" "Presa Trovejante"
   "thunder-punch" "Soco Trovoada"
   "thunder-shock" "Choque do Trovão"
   "thunder-wave" "Onda de Choque"
   "thunderbolt" "Relâmpago"
   "thunderclap" "Estrondo de Trovão"
   "thunderous-kick" "Chute Trovejante"
   "tickle" "Cócegas"
   "tidy-up" "Arrumar"
   "topsy-turvy" "Reviravolta"
   "torch-song" "Canção Ardente"
   "torment" "Tormento"
   "toxic" "Tóxico"
   "toxic-spikes" "Espinhos Tóxicos"
   "toxic-thread" "Fio Tóxico"
   "trailblaze" "Desbravar"
   "transform" "Transformação"
   "tri-attack" "Triataque"
   "trick" "Truque"
   "trick-or-treat" "Doces ou Travessuras"
   "trick-room" "Espaço de Truques"
   "triple-arrows" "Flechas Triplas"
   "triple-axel" "Pinote Triplo"
   "triple-dive" "Mergulho Triplo"
   "triple-kick" "Chute Triplo"
   "trop-kick" "Chute Tropical"
   "trump-card" "Trunfo"
   "twin-beam" "Raio Gêmeo"
   "twineedle" "Agulha Dupla"
   "twinkle-tackle--physical" "Investida Cintilante (Físico)"
   "twinkle-tackle--special" "Investida Cintilante (Especial)"
   "twister" "Tornado"
   "u-turn" "Meia-volta"
   "upper-hand" "Supermão"
   "uproar" "Alvoroço"
   "v-create" "Criação V"
   "vacuum-wave" "Onda de Vácuo"
   "veevee-volley" "Rajada Eevee"
   "venom-drench" "Banho de Veneno"
   "venoshock" "Choque Venenoso"
   "vice-grip" "Aperto"
   "victory-dance" "Dança da Vitória"
   "vine-whip" "Chicote de Cipó"
   "vital-throw" "Arremesso Vital"
   "volt-switch" "Troca Elétrica"
   "volt-tackle" "Investida Trovão"
   "wake-up-slap" "Tapa Despertador"
   "water-gun" "Jato de Água"
   "water-pledge" "Pacto de Água"
   "water-pulse" "Pulso d'Água"
   "water-shuriken" "Estrela Ninja de Água"
   "water-sport" "Banho de Água"
   "water-spout" "Jorro de Água"
   "waterfall" "Cachoeira"
   "wave-crash" "Choque de Ondas"
   "weather-ball" "Esfera Climática"
   "whirlpool" "Redemoinho Aquático"
   "whirlwind" "Redemoinho"
   "wicked-blow" "Golpe Perverso"
   "wicked-torque" "Torque Perverso"
   "wide-guard" "Proteção Ampla"
   "wild-charge" "Ataque Selvagem"
   "wildbolt-storm" "Tempestade Chocante"
   "will-o-wisp" "Fogo-fátuo"
   "wing-attack" "Ataque de Asa"
   "wish" "Desejo"
   "withdraw" "Recolher"
   "wonder-room" "Espaço Maravilhoso"
   "wood-hammer" "Martelo de Madeira"
   "work-up" "Motivação"
   "worry-seed" "Semente da Preocupação"
   "wrap" "Embrulho"
   "wring-out" "Espremer"
   "x-scissor" "Tesoura X"
   "yawn" "Bocejo"
   "zap-cannon" "Canhão Zap"
   "zen-headbutt" "Cabeçada Zen"
   "zing-zap" "Zigue-zague Elétrico"
   "zippy-zap" "Choque Veloz"})

(defn- normalizar-nome [nome]
  (-> (or nome "") str/trim str/lower-case (str/replace #"[ _]+" "-")))

(def ^:private aliases
  (merge (into {} (map (fn [[slug _]] [(normalizar-nome (str/replace slug "-" " ")) slug]) nomes-pt))
         (into {} (map (fn [[slug nome]] [(normalizar-nome nome) slug]) nomes-pt))
         {"revólver-d'água" "water-gun" "chicote-de-vinha" "vine-whip"
          "trovoada-de-choques" "thunder-shock"}))

(defn identificador [nome]
  (let [chave (normalizar-nome nome)]
    (if (contains? nomes-pt chave) chave (get aliases chave chave))))

(defn chave [golpe]
  (identificador (or (:slug golpe) (:nome-exibicao golpe))))

(defn traduzir [golpe]
  (let [slug (chave golpe)]
    (assoc golpe :slug slug :nome-exibicao (get nomes-pt slug (:nome-exibicao golpe)))))

(defn unicos [golpes]
  (second (reduce (fn [[vistos resultado] golpe]
                    (let [id (chave golpe)]
                      (if (contains? vistos id) [vistos resultado]
                        [(conj vistos id) (conj resultado (traduzir golpe))])))
                  [#{} []] golpes)))

(defn ataque-do-tipo? [golpe tipos]
  (and (contains? (set tipos) (:tipo golpe))
       (contains? #{:fisico :especial} (:classe golpe))
       (pos? (or (:poder golpe) 0))))
